### ISSUE TITLE
duplicating or importing a checkmark activity reverses the order of examples

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#38] opened 2019-07-29 10:24 UTC
seems like #23 is not completely fixed yet :/

tested with checkmark 2019012000 on both moodle 3.6.3 and moodle 3.7.1

if i create a checkmark mod with any number of examples, the examples display in correct order, eg:

- example 1
- example 2
- example 3

if i now duplicate this activity, the order of the examples will be reversed:

- example 3
- example 2
- example 1

**Comment by goggo24** [comment] 2019-08-27 18:43
Thanks for reporting. I couldn't reproduce the bug  in ours system (MySql) - could you try it with the newest checkmark version 3.7.0?

**Comment by stemiwe** [comment] 2019-09-09 11:56
i just tried with 3.7.0 in Moodle 3.7 and it's the same problem. we use posgresql.

i remember when i first reported this bug you could not reproduce it either - must be some weird database thing :/

**Comment by goggo24** [comment] 2020-02-26 21:20
We still cannot reproduce the behavior :(

**Comment by stemiwe** [comment] 2020-02-27 08:02
just tried again with Moodle 3.8.1+ (Build: 20200130) and checkmark v3.8.0 (2020020500) on our test server with PHP 7.3 and postgres - still the same behaviour 

very curious indeed :(

**Comment by jondo** [comment] 2020-04-28 10:08
I also see this issue, but I don't know about the database used here.

**Comment by jondo** [comment] 2020-10-13 11:08
Importing from another course also creates this bug.

Even if you cannot reproduce this behavior: Would it be possible to _additionally store the example order explicitly_, and to use this information for explicit sorting later on?

**Comment by h3ssto** [comment] 2020-11-20 10:59
The Moodle at Ulm University faces the same issue. It occurs when duplicating an activity or importing it from another course or the "Sharing Cart".

**Comment by goggo24** [comment] 2020-11-20 11:37
@h3ssto do you also use posgresql?

**Comment by abias** [comment] 2020-11-20 13:46
Hey @goggo24 -

> do you also use posgresql?

Yes, we do!

**Comment by jondo** [comment] 2021-03-19 08:39
I am using the workaround of creating a "duplicate of the duplicate". Maybe this could be implemented internally as "hacky" fix?

**Comment by h3ssto** [comment] 2021-03-19 12:38
It is beyond me why this got labeled with `wontfix` when this should be a straightforward fix.

**Comment by jondo** [comment] 2021-04-01 07:54
Forget the "duplicate of a duplicate" hack: I just (for the first time) saw the example order not only reversed, but permuted to 3,1,5,4,2 in the duplicate 🙈

(This is on Moodle 3.8.x, with Checkmark 3.8.0.)

**Comment by lukasnoebauer** [comment] 2021-08-26 09:35
We also encounter this bug with Moodle 3.10.6, Checkmark v3.10.1 and PostgreSQL database.

**Comment by jondo** [comment] 2021-08-26 11:14
@lukasnoebauer, thank you for additional testing with our instance here in Linz.

@goggo24, please reopen this issue. We have reports from Moodle instances of three different institutions here, so it is certainly valid even if you cannot reproduce it yet.

**Comment by jondo** [comment] 2021-09-10 12:57
Without this bug, I could reuse much larger parts of past courses. Instead, I have to [mass-delete](https://moodle.org/plugins/block_massaction#yui_3_17_2_1_1631278543340_172) and recreate all the checkmark activities. :-(

**Comment by jondo** [comment] 2022-09-05 12:01
@stemiwe, can you please update this issue's title to "duplicating or importing ..."?

**Comment by h3ssto** [comment] 2022-09-05 13:31
@jondo I see we are both preparing for the new term :sweat_smile:. Can reproduce when importing and duplicating. 

Moodle 3.9 + postgresql

**Comment by stemiwe** [comment] 2022-09-06 07:20
@jondo I updated the title.

**Comment by jondo** [comment] 2022-09-06 10:54
@goggo24 , please reopen this.

**Comment by goggo24** [comment] 2022-09-08 21:19
After we release a version 4.0.0 of checkmark, we'll take a closer look at this issue.

**Comment by jondo** [comment] 2023-03-10 12:30
@goggo24 Great! (Version 4.0.0 was released on 2022-10-01, see the [versions on moodle.org](https://moodle.org/plugins/mod_checkmark/versions).)

**Comment by mwreichel** [comment] 2023-11-09 10:48
hi,
we tried to reproduce the bug using the current v4.2.0 to be able to fix it finally. now we also use postgresql to check it easier, but i wasn't able to reproduce it yet by importing activites, duplicate, duplicate a duplicate,...

@stemiwe: please could you (or anyone else) check, whether this bug still occurs.
thanks.

**Comment by jondo** [comment] 2023-11-09 14:18
I also cannot reproduce this issue with our instance, which now is Moodle 4 (4.1.5 or later). Both duplicating and importing now works!

**Comment by mwreichel** [comment] 2023-11-13 08:53
Hi,
great - thanks for checking this.
I will leave the issue open for a few more days and would close it afterwards.

**Closed as completed** 2023-11-17 14:23 UTC
Labels: PostgreSQL
