### ISSUE TITLE
Unable to import lang/en/checkmark.php into AMOS

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-mod_checkmark#13] opened 2015-09-03 20:37 UTC
AMOS reports syntax issues at the line 45 of the strings file. But this time I believe it is actually a bug in the AMOS parser itself (probably caused by the presence of escaped single quote characters). I can import the file manually if required unless the situation is sorted out. Please let me know. Thanks, and sorry for this.

**Comment by kaspot** [comment] 2015-09-04 06:31
thanks - we will check the lang strings

**Comment by mkemmerling** [comment] 2015-09-10 11:31
Hi David,
We haven't modified the lang strings, but the german lang file has now been accepted by the maintainer, so it looks like the problem is resolved in AMOS? Can you confirm this?

**Comment by mudrd8mz** [comment] 2015-09-10 14:05
Ah, I can see it now. I can confirm the version for Moodle 2.8 https://moodle.org/plugins/pluginversion.php?id=9253 has been successfully imported into AMOS. It is just the version for 2.6 and 2.7 https://moodle.org/plugins/pluginversion.php?id=7021 that could not be imported as it is still using the concatenation operator `.` - see https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

To have this fully sorted out, you may want to release a fix version to replace the current one for 2.6 and 2.7 - something like `2014052106` maybe?

**Comment by kaspot** [comment] 2015-09-10 14:11
ok great for the clarification - I will update our developer on that one. Thanks.

**Comment by kaspot** [comment] 2015-10-06 14:31
Should be fixed.

**Closed as completed by kaspot** 2015-10-06 14:31 UTC
